INSERT INTO AUTHORITY(AUTHORITY_ID, NAME) VALUES (1, 'ADMIN');
INSERT INTO AUTHORITY(AUTHORITY_ID, NAME) VALUES (2, 'READER');

INSERT INTO USERS(USER_ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
VALUES (1, 'admin', '$2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu', FALSE, FALSE, FALSE, TRUE);
INSERT INTO USERS(USER_ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
VALUES (2, 'user', '$2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (2, 2);

-- CATEGORY
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (1, 'Продукты', '', 'Обычные продукты');
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (2, 'Химия', '', 'Обычная химия');