-- CATEGORY
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (1, 'Продукты', '', 'Обычные продукты');
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (2, 'Химия', '', 'Обычная химия');