-- CATEGORY
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (1, 'Продукты', '', '');
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (2, 'Ипотека', '', '');
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (3, 'Косметика и химия', '', '');
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (4, 'Квартплата', '', '');
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (5, 'Связь и интернет', '', '');
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (6, 'Здоровье', '', '');
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (7, 'Одежда и обувь', '', '');
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (8, 'Транспорт', '', '');
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (9, 'Подарки', '', '');
INSERT INTO CATEGORY (CATEGORY_ID, MAIN_CATEGORY, SUB_CATEGORY, DESCRIPTION) VALUES (10, 'Развлечения', '', '');
